# Copyright (c) 2019-2020-2021 Luca Cappa
# Copyright (c) 2021 AICDG
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: Build with CMake
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    env:
      vulkan-ver: 1.2.182.0
      VULKAN_SDK: "C:\\VulkanSDK\\1.2.182.0"
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
            cxx: cl.exe
            cc: cl.exe

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set Compiler Environment
        uses: lukka/set-shell-env@v1
        with:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}

      - name: vulkansdk
        if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{ env.vulkan-ver }}/windows/VulkanSDK-${{ env.vulkan-ver }}-Installer.exe?Human=true -OutFile VulkanSDK-${{ env.vulkan-ver }}-Installer.exe
          $installer = Start-Process -FilePath VulkanSDK-${{ env.vulkan-ver }}-Installer.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();

      - name: Run CMake+Ninja
        uses: lukka/run-cmake@main
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '--config RelWithDebInfo -j 2'
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
